language: ruby

rvm: 2.2.2

cache:
  bundler: true

addons:
  postgresql: 9.3

env:
  global:
  - DATABASE_URL='postgres://'
  - COVERAGE='1'
  matrix:
  - INTEGRATION_SPECS='1'
  - INTEGRATION_SPECS='0'

before_script:
- psql < db/schema.sql
