language: ruby

rvm: 2.3.1

cache:
  bundler: true

addons:
  postgresql: 9.3

env:
  global:
  - DATABASE_URL='postgres://job_board_test'
  - COVERAGE='1'
  matrix:
  - INTEGRATION_SPECS='1'
  - INTEGRATION_SPECS='0'

before_script:
- cpanm --quiet --notest 'App::Sqitch'
- createdb job_board_test
- pushd db && sqitch deploy && sqitch verify ; popd
